### ISSUE TITLE
Feature request: configuration by server response

### ISSUE THREAD

**Issue by punund** [aaronpk/Overland-iOS#99] opened 2020-05-05 23:12 UTC
Hello and thank you for the wonderful software.

What I would like to see is the ability to adjust some settings by server responses, e.g.

````json
{ "result": "ok",
  "command": {
     "sendInterval": 20
     }
}
````

This would allow to track approach to a point of interest wich cannot be triggered by "significant location change".

Related to #94

**Comment by aaronpk** [comment] 2024-04-27 17:30
Closing as duplicate of #94

**Closed by aaronpk** 2024-04-27 17:30 UTC
Labels: duplicate

**Comment by aaronpk** [comment] 2024-04-27 23:53
This is done now! Check out the readme for details:

https://github.com/aaronpk/Overland-iOS?tab=readme-ov-file#configuration-by-server-response
